/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
// const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  // docs: [
  //   {
  //     type: 'category',
  //     label: 'Guides',
  //     collapsible: true,
  //     collapsed: false,
  //     items: [
  //       'creating-pages',
  //       {
  //         type: 'category',
  //         label: 'Docs',
  //         items: ['introduction', 'sidebar', 'markdown-features', 'versioning'],
  //       },
  //     ],
  //   },
  // ],
  
  // tutorialSidebar: [
  //   'intro',
  //   'hello',
  //   {
  //     type: 'category',
  //     label: 'Tutorial',
  //     items: ['tutorial-basics/create-a-document'],
  //   },
  // ],
   
// };

module.exports = {
  secretarySidebar: [
    'secretary/index',
    'secretary/triage',
    'secretary/fiche',
    'secretary/schedule',
    'secretary/report-social',
    'secretary/habitation',
    'secretary/sporadic',
    'secretary/benefit-eventual',
    'secretary/cadastro-unico',
    'secretary/solicitation-visit',
  ],

  crasSidebar: [

    'cras/index',
    'cras/triage/create',
    

      // {
      //   type: 'link',
      //   docId: 'cras/triage/create',
      //   label: 'Triagem',
      //   position: 'left',
      // },

    // {
    //   type: 'category',
    //   label: 'Triagem',
    //   items: ['cras/triage/create'],
    // },

  ],

};

// module.exports = sidebars;
